[package]
name = "evalbot"
version = "0.2.2"
authors = ["angelsl <hidingfromhidden@gmail.com>"]

[features]
unixsocket = ["evalbotlib/unixsocket"]

[dependencies]
evalbotlib = { path = "../evalbotlib" }
irc = ">= 0.10.1"
clippy = ">= 0.0.24"
rustc-serialize = ">= 0.3.16"
