[package]
name = "evalbotlib"
version = "0.3.0"
authors = ["angelsl <angelsl@in04.sg>"]

[features]
unixsocket = []

[dependencies]
toml = "0.4"
serde = "1"
serde_derive = "1"
byteorder = "1"
tokio = "0.1"
tokio-process = "0.2"
futures = "0.1"
log = "0.4"
